//var periods = periodsCreate(201201,35);
var periods = { mth : [201506130], ndx : { 20150630 : 0 }};
console.log(periods);

var dims = {
    "mre":{"display":"mre","value":0},
    "set":{"display":"Status","value":1},
    "tDayOfWeek":{"display":"Day #","value":2},
    "daysOfWeek":{"display":"Day","value":3},
    "monthsOfYear":{"display":"Month","value":4},
    "tmonth":{"display":"Month #","value":5},
    "tyear":{"display":"Year","value":6},
    "tWeekOfMonth":{"display":"Week of Mth","value":7},
    "tWeekOfYear":{"display":"Week of Yr","value":8},
    "CHANNEL":{"display":"Channel","value":9},
    "BRANCH_REGION":{"display":"Region (Chnl)","value":10},
    "BRANCH_NAME":{"display":"Unit","value":11},
    "PORTFOLIO":{"display":"Portfolio","value":12},
    "REPORTING_CATEGORY":{"display":"Category","value":13},
    "STAGE_PAYMENT_FLAG":{"display":"Stage Pmt","value":14},
    "LOAN_TYPE":{"display":"Loan Type","value":15},
    "TOP_UP_FLAG":{"display":"Top Up","value":16},
    "LOAN_SIZE_BANDS":{"display":"Loan Size","value":17},
    "LTV_BAND":{"display":"LTV Band","value":18},
    "LTI_BAND":{"display":"LTI Band","value":19},
    "RATE_TYPE":{"display":"Rate Type","value":20},
    "TERM_BANDS":{"display":"Term Band","value":21},
    "REPAYMENT_TYPE":{"display":"Repay Type","value":22},
    "IRB_CLASS":{"display":"IRB","value":23},
    "PROPERTY_STYLE":{"display":"Property Style","value":24},
    "NUM_BEDROOMS":{"display":"# Beds","value":25},
    "COUNTY_AREA":{"display":"County (sec)","value":26},
    "FUNDED_POST_REGS_FLAG":{"display":"Funded Post Regs","value":27},
    "DUAL_BREACH_FLAG":{"display":"Dual Breach","value":28},
    "LTV_IN_SCOPE_FOR_REGS":{"display":"Reg Scope (LTV)","value":29},
    "LTV_BREACH_FLAG":{"display":"LTV Breach","value":30},
    "LTI_IN_SCOPE_FOR_REGS":{"display":"Reg Scope (LTI)","value":31},
    "LTI_BREACH_FLAG":{"display":"LTI Breach","value":32}
    };

var mres = {
    "LOAN_AMOUNT":{"display":"LOAN_AMOUNT","value":0},
    "CURRENT_LOAN_BALANCE":{"display":"CURRENT_LOAN_BALANCE","value":1},
    "PROPERTY_VALUE":{"display":"PROPERTY_VALUE","value":2},
    "ACTUAL_LTV":{"display":"ACTUAL_LTV","value":3},
    "WEIGHTED_LTV_CALC":{"display":"WEIGHTED_LTV_CALC","value":4},
    "ACTUAL_LTI":{"display":"ACTUAL_LTI","value":5},
    "WEIGHTED_LTI_CALC":{"display":"WEIGHTED_LTI_CALC","value":6},
    "EW_INT_RATE":{"display":"EW_INT_RATE","value":7},
    "EW_TERM":{"display":"EW_TERM","value":8},
    "OFFER_TO_FUND_IN_DAYS":{"display":"OFFER_TO_FUND_IN_DAYS","value":9},
    "LTV_BREACH_AMOUNT":{"display":"LTV_BREACH_AMOUNT","value":10},
    "LTI_BREACH_AMOUNT":{"display":"LTI_BREACH_AMOUNT","value":11},
    "ACTUAL_SCORE":{"display":"ACTUAL_SCORE","value":12},
    "LIVING_AREA_SQ_M":{"display":"LIVING_AREA_SQ_M","value":13},
    "AGE_OF_VAL_AT_FUNDING_IN_DAYS":{"display":"AGE_OF_VAL_AT_FUNDING_IN_DAYS","value":14},
    };

var dimOrder = {
    "set":["Funded","Offer","Application"],
    "tyear":[2013,2014,2015],
    "monthsOfYear":["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "daysOfWeek":["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    "tDayOfWeek":["2","3","4","5","6","7","0","1"],
    "tWeekOfMonth":[1,2,3,4,5],
    "FUNDED_POST_REGS_FLAG":["Y","N"],
    "REPORTING_CATEGORY":["FTB","STB","Switch","Neg. Eq.","CCMA","BTL"],
    "STAGE_PAYMENT_FLAG":["Y","N"],
    "TOP_UP_FLAG":["Y","N"],
    "CHANNEL":["Branch","Broker","CCMA"],
    "LOAN_TYPE":["Home Loan","N/A","Staff Loan"],
    //"PROPERTY_STYLE":["Det","Sem","End","Mid","Bun","Dup","Apa","Tow","Oth","N/A"],
    "PROPERTY_STYLE":["range","Bungalow(incl Dormer)","Detached","Semi Detached","Other","Mid Terrace","End Terrace"],
    "COUNTY_AREA":["Dublin","Wicklow","Cork","N/A","Kilkenny","Louth","Waterford","Kildare","Meath","Limerick","Clare","Galway","Offaly","Wexford","Donegal","Sligo","Kerry","Tipperary","Cavan","Roscommon","Carlow","Laois","Westmeath","Monaghan","Mayo","Longford","Leitrim"].sort(),
    "LTV_BAND":["<=50",">50<=55",">55<=60",">60<=65",">65<=70",">70<=75",">75<=80",">80<=85",">85<=90",">90<=95",">95<=100",">100%"],
    "LTV_BREACH_FLAG":["Y","N"],
    "LTI_BREACH_FLAG":["Y","N"],
    "DUAL_BREACH_FLAG":["Y","N"],
    "RATE_TYPE":["Variable","Fixed","N/A"],
    "PORTFOLIO":["H/L","BTL","N/A"],
    "IRB_CLASS":["9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"].sort(),
    "REPAYMENT_TYPE":["Principal & Interest Repayments","null"],
    "LOAN_SIZE_BANDS":["<=50K","50K-<=100K","100K-<=150K","150K-<=200K","200K-<=250K","250K-<=500K","500K-<=1M",">1M"],
    "LTI_BAND":["<=1","1-2","2-2.5","2.5-3","3-3.5","3.5-4","4-4.5","4.5-5",">5"],
    "TERM_BANDS":["<=5","6-10","11-15","16-20","21-25","26-30","31-35","36-40",">40"],
    "NUM_BEDROOMS":["1","2","3","4","5","6","7","8","10","N/A","null"]
}

//Buttons for popup chart - NEED to change so updates from dataDims names
var popBtns = [
    "RATE_TYPE",
    "TERM_BANDS",
    "REPAYMENT_TYPE",
    "LOAN_SIZE_BANDS",
    "LTV_BAND",
    "LTI_BAND",
    "IRB_CLASS",
    "PROPERTY_STYLE",
    "NUM_BEDROOMS",
    "COUNTY_AREA",
    "FUNDED_POST_REGS_FLAG",
    "DUAL_BREACH_FLAG",
    "LTV_IN_SCOPE_FOR_REGS",
    "LTV_BREACH_FLAG",
    "LTI_IN_SCOPE_FOR_REGS",
    "LTI_BREACH_FLAG"
    ];
var popBtnsA = [
    "set",
    "CHANNEL",
    "BRANCH_REGION",
    "BRANCH_NAME",
    "PORTFOLIO",
    "REPORTING_CATEGORY",
    "STAGE_PAYMENT_FLAG",
    "LOAN_TYPE",
    "TOP_UP_FLAG",
    "daysOfWeek",
    "monthsOfYear",
    "tyear",
    "tWeekOfMonth",
    "tWeekOfYear",
    ];

var filterDimsNew = {
        "set":{"colours":null, 'hide' : true},
        "tDayOfWeek":{"colours":null, 'hide' : true},
        "tWeekOfMonth":{"colours":null, 'hide' : true},
        "FUNDED_POST_REGS_FLAG":{"colours":palettes['binary'].slice(0), 'hide' : true },
        "BRANCH_NAME":{"colours":null, 'hide' : true},
        "PROPERTY_STYLE":{"colours":null, 'hide' : true},
        "LTV_BREACH_FLAG":{"colours":palettes['binary'].slice(0), 'hide' : true },
        "LTI_BREACH_FLAG":{"colours":palettes['binary'].slice(0), 'hide' : true },
        "DUAL_BREACH_FLAG":{"colours":palettes['binary'].slice(0), 'hide' : true },
        "LTV_IN_SCOPE_FOR_REGS":{"colours":palettes['binary'].slice(0), 'hide' : true },
        "LTI_IN_SCOPE_FOR_REGS":{"colours":palettes['binary'].slice(0), 'hide' : true },
    };

var filterDims = [
    "set",
    "CHANNEL",
    "BRANCH_REGION",
    "BRANCH_NAME",
    "PORTFOLIO",
    "REPORTING_CATEGORY",
    "STAGE_PAYMENT_FLAG",
    "LOAN_TYPE",
    "TOP_UP_FLAG",
    "LOAN_SIZE_BANDS",
    "LTV_BAND",
    "LTI_BAND",
    "RATE_TYPE",
    "TERM_BANDS",
    "REPAYMENT_TYPE",
    "IRB_CLASS",
    "PROPERTY_STYLE",
    "NUM_BEDROOMS",
    "COUNTY_AREA",
    "FUNDED_POST_REGS_FLAG",
    "DUAL_BREACH_FLAG",
    "LTV_IN_SCOPE_FOR_REGS",
    "LTV_BREACH_FLAG",
    "LTI_IN_SCOPE_FOR_REGS",
    "LTI_BREACH_FLAG",
    "tyear",
    "monthsOfYear",
    "tWeekOfMonth",
    "daysOfWeek",
    "tWeekOfYear"].map(function(e,i,a){
            var colours = null, hide = null;
            if(filterDimsNew[e]){
                colours = filterDimsNew[e]['colours'];
                hide = filterDimsNew[e]['hide'];
            }
            return {'name' : e, 'display' : dims[e]['display'], 'order' : dimOrder[e],  'colours' : colours, 'hide' : hide};
        });

var mekkoDims = [
    "set",
    "daysOfWeek",
    "monthsOfYear",
    "tyear",
    "tWeekOfMonth",
    "tWeekOfYear",
    "CHANNEL",
    "BRANCH_REGION",
    "BRANCH_NAME",
    "PORTFOLIO",
    "REPORTING_CATEGORY",
    "STAGE_PAYMENT_FLAG",
    "LOAN_TYPE",
    "TOP_UP_FLAG",
    "LOAN_SIZE_BANDS",
    "LTV_BAND",
    "LTI_BAND",
    "RATE_TYPE",
    "TERM_BANDS",
    "REPAYMENT_TYPE",
    "IRB_CLASS",
    "PROPERTY_STYLE",
    "NUM_BEDROOMS",
    "COUNTY_AREA",
    "FUNDED_POST_REGS_FLAG",
    "DUAL_BREACH_FLAG",
    "LTV_IN_SCOPE_FOR_REGS",
    "LTV_BREACH_FLAG",
    "LTI_IN_SCOPE_FOR_REGS",
    "LTI_BREACH_FLAG"
].map(function(e,i,a){
        return {'name' : dims[e]['display'], 'value' : e};
    });
